site:
  title: DJ Link Packet Analysis
  url: https://djl-analysis.deepsymmetry.org
  start_page: djl-analysis::mixer.adoc
content:
  sources:
  - url: https://github.com/Deep-Symmetry/dysentery.git
    branches: [master]
    start_path: doc
plugins:
  - path: ./extension
    config:
      generator: ./generator
      name: bytefield
  - path: ./antora-lunr
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle.zip
    snapshot: true
